apiVersion: v1
kind: Service
metadata:
  name: myjan-service
spec:
  selector:
    name: myjan
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # This will expose the service to external traffic
